repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        name: Clang Format
        args: [--style=file]
        files: \.(cpp|hpp|h|c|cc)$

  - repo: local
    hooks:
      - id: cppcheck
        name: Cppcheck
        entry: cppcheck --force --quiet --language=c++
        language: system
        files: \.(cpp|hpp|h|c|cc)$

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: Black
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-xml
      - id: check-merge-conflict


  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    - id: cmake-format
    - id: cmake-lint


